### ISSUE TITLE
CLi saves context incorrectly as "default" in NYC

### ISSUE THREAD

**Issue by mciverza** [civo/cli#48]
The kubeconfig file for clusters in NYC is different.

Note that the two clusters referenced below are on different K3s versions. I will upgrade and re-test

E.g output for a cluster in SVG1:

```
civo@krew:~$ civo k3s show observe4
          ID : f3abcc09-4a4e-4b0f-a74e-8b9e0a71c323
        Name : observe4
       Nodes : 1
        Size : g2.medium
      Status : ACTIVE
     Version : 1.18.6+k3s1 *
```
civo k3s config observe4

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <snip>
    server: https://185.136.235.229:6443
  name: observe4
contexts:
- context:
    cluster: observe4
    user: observe4
  name: observe4
current-context: observe4
kind: Config
preferences: {}
users:
- name: observe4
  user:
    password: <snip>
    username: <snip>

```

whereas in NYC
```
civo@krew:~$ civo k3s show testcli06
          ID : ae1c1bad-174b-4f93-ab9d-514aba8c1165
        Name : testcli06
       Nodes : 2
        Size : g3.medium
      Status : ACTIVE
     Version : 1.20.0-k3s2
```

```
civo@krew:~$ civo k3s config testcli06
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <snip>
    server: https://212.2.243.66:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: <snip>
    client-key-data: <snip>
```
